services:
  postgresqldb:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: clothingsdb
      PGDATA: /data/postgres
    volumes:
      -  clothings_data:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - db
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    depends_on:
      - postgresqldb
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
#      PGADMIN_HOST: postgresqldb
    volumes:
      - clothings_data:/var/lib/pgadmin
    networks:
      - db

  jenkins:
    image: jenkins/jenkins
    container_name: jenkins-container
#    user: root
#    privileged: true
    restart: always
    ports:
      - "8085:8080"
      - "50000:50000"
    volumes:
      - clothings_data:/var/jenkins_home
    networks:
      - db

  clothingapp:
      image: 'clothingapp:v1'
      build:
        context: .
      container_name: clothingapp
      depends_on:
        - postgresqldb
      environment:
        - POSTGRES_USER=${POSTGRES_USER}
        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresqldb:5432/clothingsdb
        - SPRING_DATASOURCE_USERNAME=${POSTGRES_USER}
        - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}
        - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      ports:
        - "8081:8080"

networks:
  db:
    driver: bridge

volumes:
  clothings_data:

