server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://postgresqldb:5432/clothingsdb?createDatabaseIfNotExist=true
    username: Godwin
    password: secret
    port: 5432
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show_sql: true
  main:
    web-application-type: servlet